version: '3.8'

services:
  app:
    build: .
    container_name: node_app_container
    env_file:
      - .env
    ports:
      - "3014:3014"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: unless-stopped
